name: build-and-push-docker-image
on:
  workflow_run:
    workflows: [test-backend]
    types: [completed]
  #to begin you want to launch this job in main and develop
  push:
    branches: main
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./BackEnd
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-epf:backend
          # Note: tags has to be all lower-case
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./Database
          # relative path to the place where source code with Dockerfile is located
          # Note: tags has to be all lower-case
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tp-devops-epf:database
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./Front
          # Note: tags has to be all lower-case
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tp-devops-epf:httpd
          push: ${{ github.ref == 'refs/heads/main' }}
